#________________________________________
#
#

include				$(MAKE_PATH)/common.mk

BUILD_ARTIFACT			= $(TARGET_BUILD_PATH)/$(TARGET_NAME)
CONFIGURE_ARTIFACT		= $(TARGET_BUILD_PATH)/Makefile
EXTRACT_ARTIFACT		= $(CONFIGURE_ARTIFACT).in
INSTALL_ARTIFACT		= $(INSTALL_BIN_PATH)/$(TARGET_NAME)
TARGET_BUILD_PATH		= $(BUILD_PATH)/$(TARGET_NAME_VERSION)
TARGET_NAME			= tmux
TARGET_NAME_VERSION		= $(TARGET_NAME)-$(TARGET_VERSION)
TARGET_TARBALL_NAME		= $(TARGET_NAME_VERSION).tar.gz
TARGET_TARBALL_PATH		= $(SOURCE_PATH)/$(TARGET_TARBALL_NAME)
TARGET_VERSION			= 1.9a

#________________________________________
#
#

$(TARGET_NAME): $(INSTALL_ARTIFACT)

$(EXTRACT_ARTIFACT): $(TARGET_TARBALL_PATH)
	tar zxf $< -C $(BUILD_PATH)

$(CONFIGURE_ARTIFACT): $(EXTRACT_ARTIFACT)
	cd $(TARGET_BUILD_PATH); LIBEVENT_CFLAGS='-I$(INSTALL_INCLUDE_PATH) -I/usr/include' LIBEVENT_LIBS='-L$(INSTALL_LIB_PATH) -levent' ./configure --prefix=$(INSTALL_PATH) --enable-static

$(BUILD_ARTIFACT): $(CONFIGURE_ARTIFACT)
	cd $(TARGET_BUILD_PATH); make

$(INSTALL_ARTIFACT): $(BUILD_ARTIFACT)
	cd $(TARGET_BUILD_PATH); make install

clean:
	-rm -rf $(TARGET_BUILD_PATH)

#
#
#

